name: Signal Messenger Receiver
url: https://github.com/Tsjippy/ha-addons/tree/main/signal-reply
version: 1.0.14
slug: signal_receiver
arch:
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

description: Signal Messenger Receiver Home Assistant Addon
startup: services

options:
  log level: null
  signal_port: 8080
  signal_number: ''
  messages: 
    - message: I am currently not able to respond, but will respond as quickly as possible
      languague: en
  google_label: ''
  client_id: null
  client_secret: null
  project_id: null
  port: 7070

schema:
  log level: list(debug|info|warning|error)
  signal_port: int
  signal_number: str
  messages:
    - languague: str
      message: str
  google_label: str?
  client_id: str?
  client_secret: str?
  project_id: str?
  port: int(2,99999)?

init: false

ports:
  7070/tcp: 7070


hassio_api: true
homeassistant_api: true

image: "ghcr.io/tsjippy/{arch}-signal-receiver"