# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debiab-base/amd64:stable
  armhf: ghcr.io/hassio-addons/debian-base/armhf:stable
  armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  i386: ghcr.io/hassio-addons/debian-base/i386:stable
labels:
  org.opencontainers.image.title: "Whatsapp Add-on"
  org.opencontainers.image.description: "Whatsapp integration for Home Assistant."
  org.opencontainers.image.source: "https://github.com/tsjippy/whatsapp-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
