name: "Birthdays"
description: "Imports Google Contacts into Home Assistant and sends automated birthday messages"
version: "1.1.4"
slug: "birthdays"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  9090/tcp: 9090

options:
  debug: true
  client_id: null
  client_secret: null
  project_id: null
  hour: 10
  minutes: 00
  messages: []
  signal_numbers: []
  signal_groups: []
  whatsapp_groups: []
  log_level: null
  signal_port: 8080
  whatsapp_port: 3000

schema:
  debug: bool
  client_id: str
  client_secret: str
  project_id: str
  hour: int(0,23)
  minutes: int(0,59)
  messages:
    - languague: str(2,2)
      message: str
  signal_numbers:
    - str?
  signal_groups:
    - group_id: str?
      label_id: str?
      languague: str?
  whatsapp_groups:
    - group_name: str?
      group_id: str?
      label_id: str?
      languague: str?
  log_level: list('info'|'warning'|'error')
  signal_port: int?
  whatsapp_port: int?

map:
  - share:rw
  
image: "ghcr.io/tsjippy/{arch}-birthdays"