name: "Birthdays"
description: "Imports Google Contacts into Home Assistant and sends automated birthday messages"
version: "1.1.61"
slug: "birthdays"
url: https://github.com/Tsjippy/ha-addons/tree/main/birthdays
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  9090/tcp: 9090

options:
  client_id: null
  client_secret: null
  project_id: null
  hour: 10
  minutes: 00
  messages: []
  signal_numbers: []
  signal_groups: []
  whatsapp_groups: []
  log_level: null
  signal_port: 8080
  whatsapp_port: 3000
  port: 9090

schema:
  client_id: str
  client_secret: str
  project_id: str
  hour: int(0,23)
  minutes: int(0,59)
  messages:
    - languague: str
      message: str
  signal_numbers:
    - str?
  signal_groups:
    - group_id: str
      label_id: str
      languague: str
  whatsapp_groups:
    - group_name: str?
      group_id: str
      label_id: str
      languague: str
  log_level: list(debug|info|warning|error)
  signal_port: int(2,99999)?
  whatsapp_port: int(2,99999)?
  port: int(2,99999)?

map:
  - share:rw

hassio_api: true
homeassistant_api: true
hassio_role: admin
  
image: "ghcr.io/tsjippy/{arch}-birthdays"
